### PR TITLE
Torque balancing joint control

### PR DESCRIPTION
**Pull request by francesco-romano**

### CODE REVIEW

**Comment by traversaro** [comment]
It would be nice to have a brief list of the controllers in the main README.md , with relative links to the controller README.md . This should also be easy to integrate with the doxygen documentation.

**Comment by francesco-romano** [comment]
I think it is time to merge.

@traversaro @DanielePucci ?

**Comment by traversaro** [comment]
Ok, we need to solve the conflicts.

**Comment by francesco-romano** [comment]
Conflict solved manually.

If @DanielePucci tries the controller on the robot today we can merge it

**Comment by DanielePucci** [comment]
@gabrielenava, can you take care of these tests today?

**Comment by gabrielenava** [comment]
today the robot is not working, I'll do the tests tomorrow if it's possible

**Pull request merged**
